### ISSUE TITLE
Help Wanted - Running on Visual Studio

### ISSUE THREAD

**Issue by Zulfi2003** [RamezzE/MazeSolver#1]
not able to clone and build on windows visual studio.Many errors are coming.It will be helpful if you help to sort it and implement it

**Comment by RamezzE** [comment]
I tried to run it myself but there is a thread issue on visual studio specifically that I can't seem to overcome. I can make it work fine with CLion if that's an option for you to use. If so, I'll update the repo to include a proper CMakeLists.txt file.

Back to Visual Studio: I'll let you know how to handle all other issues while I keep researching that last issue.

1. Download SFML (the correct version that works with Visual Studio)
2. Create a Visual Studio C++ Project
3. In Project -> Properties:
    - Make sure the Configuration is set to All Configurations
    - In Configuration Properties - > General, change the C++ Language Standard to C++ 17
    - In C/C++ -> General, add your SFML include path to the Additional Include Directories section. Example: `D:\SFML- 
       2.5.1\include`
    - In C/C++ -> Preprocesser, add `SFML_STATIC;` to Preprocesser Definitions
    - In Linker -> General, add your SFML lib path to the Additional Library Directories. Example: `D:\SFML-2.5.1\lib`
    - In Linker -> Input, in the Additional Dependencies, add the following: `sfml-graphics-s.lib;sfml-window-s.lib;sfml-system-s.lib;opengl32.lib;winmm.lib;gdi32.lib;sfml-main.lib;freetype.lib;`
    - Switch to Debug Configuration and then add the following: `sfml-graphics-s-d.lib;sfml-window-s-d.lib;sfml-system-s-d.lib;opengl32.lib;winmm.lib;gdi32.lib;sfml-main.lib;freetype.lib;` to be able to debug

4. Manually create the needed classes & header files inside the Visual Studio Project. Make sure the header files are .hpp and not .h and make sure spelling of files and classes is correct.
5. Clone the repository and overwrite the empty classes you created. (Open file explorer and copy over the files - only after you create them in the Visual Studio Project, so they can be detected)
6. If Visual Studio cannot read "unistd.h", replace it with "windows.h" and replace 'usleep' with 'Sleep' since it won't be able to read it anymore.

These are all the issues that I tackled while trying to run on Visual Studio except one last thread issue that I couldn't resolve. Please tell me if these steps help in making any progress and if there are any other issues as well.

**Comment by Zulfi2003** [comment]
Thanks for the help.
